import React from 'react';

import Card from 'react-bootstrap/Card';

const ContractFormText = ({ name, address, phone, license }) => (
  <Card.Body>
    <Card.Title>Customer Information:</Card.Title>
    <Card.Text>Name: {name}</Card.Text>
    <Card.Text>Address: {address}</Card.Text>
    <Card.Text>Driver's License Number: {license.number}</Card.Text>
    <Card.Text>Phone Number: {phone}</Card.Text>
    <Card.Text>Insurance and License Information: (see below)</Card.Text>
  </Card.Body>
);

const VehicleInfoForm = ({ out, due, vin, plate, year, make, model, color, milesAllowed, mileageOut, rate, fuel, notes }) => (
  <Card.Body>
    <Card.Title>Vehicle Information:</Card.Title>
    <Card.Text>Date and Time Out: {out}</Card.Text>
    <Card.Text>Date and Time Due In: {due}</Card.Text>
    <Card.Text>Vehicle VIN: {vin}</Card.Text>
    <Card.Text>License No.: {plate}</Card.Text>
    <Card.Text>Year: {year}</Card.Text>
    <Card.Text>Make: {make}</Card.Text>
    <Card.Text>Model: {model}</Card.Text>
    <Card.Text>Color: {color}</Card.Text>
    <Card.Text>Miles Allowed: {milesAllowed}</Card.Text>
    <Card.Text>Mileage Out: {mileageOut} </Card.Text>
    <Card.Text>Rate Per Day (in dollars): {rate}</Card.Text>
    <Card.Text>Fuel: {fuel}</Card.Text>
    <Card.Text>Other Notes: {notes}</Card.Text>
  </Card.Body>
);

const PreambleText = () => (
  <Card.Body>
    <p><strong><u>Washington Vehicle Use Agreement Terms and Conditions ("Terms and Conditions")</u></strong></p>
    <ol>
      <li><strong><u>Definitions,</u></strong><strong> "Agreement" </strong>means all terms and conditions found on the "Face Page" and on all pages of these Terms and Conditions. <strong>"You" </strong>or <strong>"your" </strong>means the person identified as the Customer on the Face Page, each person signing this Agreement, every Authorized Driver and each person or organization to whom charges are billed by us at its or the Customer's direction. You are jointly and severally bound by this Agreement. <strong>"We," "us" </strong>or <strong>"our" </strong>means the independent automobile dealer or its affiliate named elsewhere in this Agreement. <strong>"Vehicle" means the </strong>automobile or truck identified in this Agreement and each vehicle we substitute for it, and all its tires, tools, accessories, equipment, keys and documents. The Vehicle may be a temporary substitute for a Customer-owned or Customer-leased vehicle that you have given us the opportunity to service or repair ("Service <strong>Replacement Vehicle"). "Rental Period" </strong>means the period from the time you take possession of the Vehicle until the time that the Vehicle is either returned to or recovered by and checked in by us. <strong>"Loss of Use" means the </strong>loss of our ability to use the Vehicle for any purpose due to damage to it or loss of it during the Rental Period, including uses other than for rental, such as display for rent or sale, opportunity to upgrade or sell, or transportation of employees. <strong>"Daily Vehicle Rate" </strong>means either: your daily time and mileage fee; or, for Service Replacement Vehicles, the daily time and mileage fee that we typically charge for vehicles of the same type as the Vehicle. <strong>"Diminished Value" means the actual cash value of the Vehicle just prior to </strong>damage or loss less the value of the Vehicle after repair or replacement. <strong>'Charges' means the fees and charges that are incurred under this Agreement. 'Vehicle License Cost Recovery Fee" means our estimate of the average per day </strong>per vehicle portion of our total annual vehicle licensing, titling, registration, plating, and inspection costs incurred in the State of Washington.</li>
      <li><strong><u>Nature of Contract; Consideration: Indemnity and Warranties,</u></strong><strong> This Agreement is a contract for rental of the Vehicle offered to you. This rental is solely a bailment for mutual consideration. By signing the Face Page, you agree to all terms and conditions of this Agreement and acknowledge that binding consideration </strong>exists, as follows: our opportunity to service or repair a vehicle you left with us; financial benefits we receive from others for the service/repair work; financial benefits we receive from others to obtain and use this Vehicle as a Service Replacement Vehicle; a fee you pay us; and/or the rights and obligations of this Agreement. <strong>To the extent permitted by law, you: (a) agree to indemnify us, defend us and hold us harmless from all claims, liability, costs and attorney fees we incur resulting from or arising out of this Agreement or your use of the Vehicle; and (b) we make no warranties, express, implied or apparent, regarding the Vehicle, no warranty of merchantability and no warranty that the Vehicle is fit for a particular purpose.</strong></li>
      <li><strong><u>Authorized Drivers,</u></strong> You represent that you are a capable and validly licensed driver.</li>
    </ol>
    <p>(a) <u>Pefinition.</u><strong> "Authorized Driver" </strong>means: (i) the Customer and the Customer's spouse or domestic partner; <strong>(ii) </strong>additional drivers listed by us in this Agreement; <strong>(iii) </strong>if the Customer is a business entity, 'Authorized Driver" includes Customer employees who are permissible drivers on the business entity's auto insurance policy; (iv) the Customer's employer, employee or coworker who is engaged in a common business activity with the Customer; <strong>(v) a </strong>licensed driver driving the Vehicle to a medical or police facility during an emergency; and <strong>(vi) a </strong>person who parks the Vehicle in a commercial establishment. <strong>(b) </strong><u>Requirements.</u> Each Authorized Driver must possess a valid driver's license and meet our age restrictions: (i) if the Vehicle is a Service Replacement Vehicle, and the Customer is the sole registered owner of a vehicle left with us for service or repair, then the Customer and the Customer's spouse or domestic partner must be at least age 18. Otherwise, the Customer and the Customer's spouse or domestic partner must be at least age 21; and <strong>(ii) </strong>an Authorized Driver defined in paragraphs 3(a)(ii) through 3(a)(iv) must be at least age 21. There are no minimum age requirements for Authorized Drivers defined in Paragraphs 3(a)(v) and 3(a)(vi). <strong>Authorized Drivers are the only persons permitted to drive the Vehicle.</strong></p>
    <ol start="4">
      <li><strong><u>Inspection; Condition and Return of Vehicle.</u></strong> You must return the Vehicle to our office on the date and time specified on the Face Page (or sooner upon our demand) with at least as much fuel as when rented, unless we offer, and you purchase, pre-paid fuel. We may repossess the Vehicle at your expense without notice to you if the Vehicle is abandoned or used in violation of law or this Agreement. You may extend the Rental Period for up to one week if you obtain our consent before the date due, and we may require you to return the Vehicle to our office for inspection. The total Rental Period may not exceed 30 days under any circumstances. The Vehicle must be returned in the same condition that you received it except for ordinary wear. If the Vehicle is retumed after closing hours, you remain responsible for all damage to or loss of it until we inspect it on reopening for business, and Charges may continue to accrue. You must obtain our prior written approval before servicing the Vehicle or replacing parts or accessories. You will check and maintain Vehicle fluid levels. You grant us, our agents, assigns and each person with a financial interest in the Vehicle the right to inspect the Vehicle during the Rental Period.</li>
      <li><strong><u>Responsibility for Damage or Loss: Reporting to Police.</u></strong><strong> Regardless of fault, you are responsible for theft or loss of the Vehicle and all damage to it, including damage caused by </strong>collision, weather, road conditions, acts of nature, theft, and vandalism. Your responsibility includes: <strong>(a) </strong>all physical damage to the Vehicle measured as follows: (i) if we determine that the Vehicle is a total loss, the actual cash value of the Vehicle; <strong>(ii) if </strong>we determine that the Vehicle is repairable: <strong>(A) the difference between the value of </strong>the Vehicle immediately before the damage and the value immediately after the damage; <strong>or (B) the reasonable </strong>estimated retail value or actual cost of repair plus Diminished Value; <strong>(b) Loss of </strong>Use, which shall be measured by multiplying the Daily Vehicle Rate by the actual or estimated number of days from the date the Vehicle is damaged until it is replaced or repaired, which you agree represents a reasonable estimate of Loss of Use damages and not a penalty. Loss of Use shall be payable regardless of fleet utilization; <strong>(c) a </strong>reasonable administrative fee; <strong>(d) towing, storage, and impound charges and other reasonable incidental and consequential damages; and (e) all costs associated with our enforcement </strong>of this Agreement or collection of Charges, including attorneys' fees, collection fees, and costs whether or not litigation is commenced. You are responsible for replacing missing equipment and Vehicle documents and keys. You must report all Vehicle accidents and incidents of theft or vandalism to us and the police upon discovery.</li>
      <li><strong><u>Prohibited Uses.</u></strong><strong> The following uses of the Vehicle are prohibited and constitute material breaches of this Agreement. The Vehicle shall not be used: (a) by anyone who is not an Authorized Driver or not licensed to drive, or by anyone whose driving license is suspended; (b) by anyone under the influence of alcohol or prescription or non-prescription drugs; (c) by anyone who obtained the Vehicle or extended the Rental Period by giving us false, fraudulent or misleading information; (d) for an illegal purpose or in the commission of a felony or other crime; (e) to carry persons or property for hire or to provide transportation network company or other transportation services; (f) to tow or to push anything; (g) in a race or speed contest; (h) to teach anyone to drive; (i) outside the United States or Canada, or outside the geographic area described elsewhere in this Agreement, if any; (0 on an unpaved surface; (k) when the odometer has been tampered with or disconnected; (I) when it is reasonable to expect you to know that further operation of the Vehicle would damage it; (m) if applicable, by anyone who lacks experience driving a vehicle with manual transmission; (n) to transport an animal (other than a service animal); (o) to carry more passengers than the number of existing seatbelts; (p) by anyone driving or operating the Vehicle while using a hand-held wireless communication device (or other device that is capable of receiving or transmitting telephonic communications, electronic data, mail or text messages) while not in a hands-free mode; (q) in a willful or reckless manner or to intentionally damage the Vehicle or cause injury or property damage to others; or (r) by anyone who is smoking, vaping, or using tobacco products in the Vehicle. PROHIBITED USE OF THE VEHICLE VIOLATES THIS AGREEMENT AND VOIDS ALL LIABILITY AND OTHER INSURANCE COVERAGE (TO THE EXTENT PERMITTED BY LAW).</strong></li>
    </ol>
    <ol start="7">
      <li>You are responsible for all damage or loss you cause to others. You agree to maintain automobile insurance during the term of this Agreement which provides to the owner, to us, and to you, the following primary coverage: (a) Bodily injury <strong>("BI") </strong>and property damage <strong>("PD") </strong>liability coverage; <strong>(b) </strong>Personal injury protection <strong>("PIP"), </strong>no-fault, or similar coverage where required; <strong>(c) </strong>Uninsured/underinsured ("UM"/"UIM") coverage where required, and <strong>(d) </strong>Comprehensive and collision damage coverage extending to the Vehicle. Your insurance coverage will provide at least the minimum limits of coverage required by the financial responsibility laws of the state where the loss occurs. <strong>Where permitted by law, by signing this Agreement, you reject UM, UIM, and supplemental no-fault or PIP coverages. </strong>Where we are required to provide such coverage, you hereby select the minimum limits required by law. Because you are providing auto insurance, we are not. In states where the law requires us to provide insurance, your insurance will be primary. Any insurance we are required to provide applies only to claims of accidental BI and PD resulting from the use of the auto, and is excess to any other valid and collectible insurance whether primary, secondary, excess or contingent. Our insurance policy contains exclusions, conditions, and limitations applicable to anyone claiming coverage. You agree to cooperate with our insurer if any claim is made, and give us immediate notice of damage, claim, or lawsuit against you. Our insurance applies only in the United States and Canada. Engaging in a Prohibited Use described in paragraph 5 or any other material breach of this Agreement will void any insurance coverage.</li>
      <li><strong><u>Reserve: Charges.</u></strong><strong> You permit us to reserve against your payment card at the time of rental a reasonable amount in addition to estimated total charges. We may use the reserve to pay all Charges. We will authorize the release of any excess reserve upon the completion of your rental. Your payment card issuer's rules will apply to your credit line or account being credited for the excess, which may not be immediately released by your card issuer. </strong>You will pay us all Charges, including: (a) taxes, surcharges, and other fees; <strong>(b) a </strong>return check fee if you pay us with a check returned unpaid; <strong>(c) </strong>all expenses we incur recovering the Vehicle if it is not returned to the renting location on the date and time promised; <strong>(d) all </strong>costs we incur collecting payment from you or otherwise enforcing our rights under this Agreement; <strong>(e) a late </strong>fee on all Charges that are not paid when due; <strong>(f) a </strong>reasonable fee to clean the Vehicle if it is returned with evidence of smoking, vaping, or animals or otherwise substantially less clean than when received by you; <strong>(g) </strong>fuel and a refueling fee if you return the Vehicle with less fuel than when received by you; <strong>(h) </strong>applicable time and mileage fee; (i) a mileage charge based on our experience if the odometer is tampered with; a) towing, storage charges, Tolls, Violations, forfeitures, court costs, penalties and all other costs we incur resulting from your use of the Vehicle; <strong>(k) </strong>a reasonable fee if you lose the keys, key fob, or toll transponder to the Vehicle; and (I) a surcharge if you do not return the Vehicle on the date and time and to the location specified on the Face Page. <strong>All Charges are subject to our final audit.</strong></li>
      <li><strong><u>Responsibility for Tolls, Traffic Violations, and Other Charges.</u></strong> You are liable for all tolls <strong>("Tolls") </strong>and parking citations, photo enforcement fees, fines for toll evasion, and other fines, fees, and penalties (each a "Violation&bull;) assessed against you, us or the Vehicle during the Rental Period. If we are notified by charging authorities that we may be responsible for payment of a Toll or Violation, you agree that we or a processing firm <strong>("Processor") </strong>may, in our sole discretion and without prior notice to you, pay the Toll or Violation plus applicable taxes on your behalf directly to the appropriate authority. If we or a Processor elect to pay a Toll or Violation, you may not be able to challenge the validity of the Toll or Violation before the charging authority. We or the Processor will charge you the face value of the Toll or Violation and any taxes, plus an administrative fee per Toll and Violation. If we or a Processor, in our sole discretion, elect to transfer liability for a Toll or Violation assessed against the Vehicle during the Rental Period to you personally, we or the Processor will charge you an administrative fee per Toll or Violation. You authorize us to release your rental and payment card information to the charging authorities and the Processor for processing and billing purposes. If we or the Processor pay a Toll or Violation, you authorize us and the Processor to charge all payments and administrative fees to the payment card you used in connection with this Agreement. <strong>Certain toll roads do not accept cash. </strong>To avoid toll violations and associated fines, fees, and taxes (and our administrative fees), you must pay all tolls with a personal transponder that is accepted on the road; use only cash lanes and pay cash; plan a route to avoid tolls; or consult local authorities for other payment methods.</li>
    </ol>
    <ul>
      <li><strong><u>Personal Property and Information.</u></strong> To the extent permitted by law, you release us, our agents. and our employees from all claims for loss of or damage to personal property that was left with us or carried in the Vehicle. If you fail to claim property left in the Vehicle for more than 30 days, we may dispose of that property in a manner we choose. You agree that we may disclose personally identifiable information about you to applicable law enforcement agencies or to our affiliates or third parties in connection with enforcement of our rights under this Agreement and for other legitimate business purposes. <strong>The Vehicle may be equipped with an infotainment system that permits you to pair your own mobile devices, and which may download your personal contacts, communications, location or other digital data. You should wipe all personal information from the Vehicle's systems before returning it.</strong></li>
      <li><strong><u>Telematics Notice and Release.</u></strong> You acknowledge that the Vehicle may be equipped with a telematics system, global positioning satellite <strong>("GPS") </strong>technology, an electronic locator device, and/or an event data recorder (collectively <strong>"Telematics System"). Your use of the Vehicle may be remotely monitored by us or on our behalf through a Telematics System to the extent permitted by law. </strong>Remote monitoring may include the collection of Vehicle data, such as location, odometer, oil life, fuel level, tire pressure, battery charge, diagnostic trouble codes, and other elements that we may deem necessary or desirable. You acknowledge that these systems may use cellular telephone, wireless technology, or radio signals to transmit data, and therefore you should have no expectation of privacy related to the use of this Vehicle. You shall inform any and all drivers and passengers of the Vehicle of the terms of this paragraph. We are not responsible for the operability of any Telematics System included with the Vehicle. To the extent permitted by law, you agree to release and indemnify, defend and hold us, the operator of the Telematics System, wireless carriers, and other suppliers of components or services harmless from any damage to persons or property caused by failure of a Telematics System to operate properly, or otherwise arising from the use of the Telematics System.</li>
      <li>No term of this Agreement can be waived or modified except by a writing that we have signed or on a form that we provide. This Agreement constitutes the entire agreement between you and us. All prior representations and agreements between you and us regarding the use of the Vehicle are void. Our waiver of a breach of this Agreement, our acceptance of payment from you, or our failure, refusal or neglect to exercise our rights under this Agreement does not constitute a waiver of another provision of this Agreement. You waive all recourse against us for criminal prosecutions we take against you for breach of this Agreement. <strong>TO THE EXTENT PERMITTED BY LAW, YOU RELEASE US FROM ALL LIABILITY FOR CONSEQUENTIAL, SPECIAL OR PUNITIVE DAMAGES IN CONNECTION WITH THIS TRANSACTION OR THE RESERVATION OR USE OF A VEHICLE. </strong>If a provision of this Agreement is deemed void the remaining provisions are valid and enforceable.</li>
    </ul>
    <p>The following are "Prohibited Uses": Use by an unauthorized driver; smoking, vaping or use of tobacco products in the Vehicle; use of the Vehicle by anyone under the influence of alcohol or prescription or non-prescription drugs; and carrying persons or property for hire or providing transportation network company or other transportation services. See Paragraph 6 of the the Terms and Conditions for other Prohibited Uses and additional information.</p>
    <p>By signing below, you: agree to the terms and conditions of this Agreement set forth on this page, and all pages of the Terms and Conditions; acknowledge that you had an opportunity to read the entire Agreement before signing; authorize us to process a separate payment card voucher in your name for all Charges, including Tolls and Violations and to release your billing/rental information to third parties for billing/processing and other legitimate purposes; permit us to reserve against your payment card the amount noted in the notes, rate per day, and fuel fields; agree that binding consideration exists, as further described in Section 2 of the Terms and Conditions of this Agreement; and authorize us to adjust your payment card account to reflect changes in amounts due or overpaid as a result of our final audit.</p>
    <p><strong>ALL CHARGES SUBJECT TO FINAL AUDIT</strong></p>
  </Card.Body>
);

const SignedUserText = ({ contract }) => (
  <Card.Body>
    <Card.Text>Signature: {contract.signature}</Card.Text>
    <Card.Text>Date: {contract.date}</Card.Text>
  </Card.Body>
);

export { PreambleText, VehicleInfoForm, ContractFormText, SignedUserText };