export const LANDING = '/';
export const ABOUT = '/about';
export const ACCOUNT = '/account';
export const ADMIN = '/admin';
export const CHOOSE_DEALER = '/choose-dealer';
export const CONFIRMATION = '/confirmation';
export const CONTACT = '/contact';
export const CONTRACT = '/contract';
export const CONTRACT_ONESHOT = '/contract/oneshot';
export const DEALER = '/dealer';
export const DEALER_ADD_USER = '/add-user';
export const LOANER_CONTRACT = '/loaner-contract';  // + /userId
export const LOANER_FLEET = '/loaner-fleet';
export const MY_CONTRACT = '/my-contract';
export const NOT_FOUND = '/not-found';
export const PRIVACY = '/privacy';
export const PASSWORD_FORGET = '/pw-forget';
export const SERVICE = '/service';
export const SIGN_IN = '/signin';
export const SIGN_UP = '/signup';
export const TERMS = '/terms';
export const TEST_DRIVE_CONTRACT = '/test-drive-contract';  // + /userId
export const USER_DETAILS = '/user-details';  // + /userId
